### ISSUE TITLE
AttributeError exception raised when using explicitly defined nested serializers

### ISSUE THREAD

**Issue by jeremystretch** [PaulGilmartin/graph_wrap#12]
Taking a step back to open a proper issue for my earlier PRs (#9 and #11). I have a nested DRF serializer for each model type, and use them to represent related objects. So for example:

```python
class NestedAuthorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name']

class BookSerializer(serializers.ModelSerializer):
    author = NestedAuthorSerializer()
    class Meta:
        model = Book
        fields = ['title', 'isbn', 'author']
```

(The actual code in use can be found [here](https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/api/serializers.py).)

Four our case, discrete nested serializers are used both to enable writability from the parent object, and to provide a "brief" format for the REST API.

When I attempt to hit the `/graphql` endpoint, an AttributeError exception is raised:

```
Traceback (most recent call last):
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 71, in graphene_object_type
    return self.type_mapping[self._graphene_type_name]

During handling of the above exception ('provider_type'), another exception occurred:
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/netbox/netbox/netbox/graphql.py", line 10, in graphql_view
    schema = schema()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/__init__.py", line 6, in schema
    return SchemaFactory.create_from_api()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/schema_factory.py", line 25, in create_from_api
    return cls(views).create()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/schema_factory.py", line 52, in create
    root_type = api_transformer.root_type()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 28, in root_type
    self._root_graphene_type_name,
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 74, in graphene_object_type
    self._add_field_data(field)
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 104, in _add_field_data
    graphene_field = field_transformer.graphene_field()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 180, in graphene_field
    self.graphene_type,
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 191, in graphene_type
    name = self._build_graphene_type_name()
  File "/home/jstretch/projects/graph_wrap/graph_wrap/django_rest_framework/api_transformer.py", line 203, in _build_graphene_type_name
    model = self._field.Meta.model.__name__.lower()

Exception Type: AttributeError at /graphql/
Exception Value: 'ListSerializer' object has no attribute 'Meta'
```

As mentioned in #9, I think the crux of the issue is that we're matching on the serializer class name to infer whether it's a nested serializer:

https://github.com/PaulGilmartin/graph_wrap/blob/cf5a534f15154db7dba6a0163f8e33b04d122978/graph_wrap/django_rest_framework/api_transformer.py#L89

Does that make sense? And is it something that can/should easily be addressed? Thanks again for your time!

**Comment by PaulGilmartin** [comment]
Thanks for clarifying! Definitely looks like an issue with the library. However I don't think the issue comes from the line `if serializer_cls_name == 'NestedSerializer': ` - as I tried to explain in the other post, that is very specifically about catching the serializers DRF creates itself when you set a depth. GraphWrap does _not_ make any assumptions about what custom serializers should be called - so the names of your serializers should make no difference. In the graph_wrap test suite we test for nested serializers in the sense you're discussing by embedding the `WrittenBySerializer` in the `PostSerializer`.

Will try dig into this a bit over the weekend when I get a chance and get back to you asap!

**Comment by PaulGilmartin** [comment]
@jeremystretch I was able to recreate this error by adding a ListSerializer to one of my test serializers. I've pushed a fix so that graph wrap now supports ListSerializers. I could not see an explicit use of ListSerializer anywhere in the netbox code, so I'm not sure exactly how you got that error, but i'm hoping since it was the same error I recreated at the same point in the code, my latest fix will work for you too.

I did try forking the netbox repo and testing myself, but I kept getting import errors (seemed like the import paths were all missing "netbox.")

**Comment by jeremystretch** [comment]
@PaulGilmartin thank you so much! Seems like your change did the trick for me. Sorry I've been a bit dense about this; I hope to dedicate some time soon to really digging into graph_wrap more.

I've got some minor issues with my DRF implementation now to dig through. Will let you know how it goes!

By the way, have you considered activating GitHub sponsorships for this project?

**Comment by PaulGilmartin** [comment]
@jeremystretch great it sorted that issue!

I haven't actually ever looked into GitHub sponsorships, but it would definitely be something I'd be open to. Couldn't find any completely clear documentation on how to go about activating it for this specific project. If I click the "get sponsored" button here https://github.com/sponsors I'm asked if I want to join a waiting list - is that the way to start?

**Comment by jeremystretch** [comment]
I believe that's it, yes. Wasn't aware they're waitlisting people now. :thinking:

**Comment by PaulGilmartin** [comment]
From what I gather, it looks like they spend some time verifying bank and tax information. I'm half way set up, will let you know how it goes!
![image](https://user-images.githubusercontent.com/18212082/121044852-eaf70f80-c7b5-11eb-954b-0ec9401ded1e.png)
